name: clean_arch_aula
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  firebase_remote_config: ^2.0.12
  hive_flutter: ^1.1.0

  flutter_modular: ^5.0.2
  modular_bloc_bind: ^1.0.1
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  dio: ^4.0.6 

  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  geolocator: ^9.0.1
  url_launcher: ^6.1.2
  mask_text_input_formatter: ^2.3.0
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  mocktail: ^0.3.0


 
flutter:
  uses-material-design: true
  
  assets:
     - assets/images/
     - .env

  
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf


 